# Generated by Django 3.0.8 on 2020-07-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo', models.TextField(max_length=100)),
            ],
        ),
    ]
